# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import test_pb2 as test__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in test_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TestServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/TestService/Connect',
                request_serializer=test__pb2.ConnectionRequest.SerializeToString,
                response_deserializer=test__pb2.ConnectionResponse.FromString,
                _registered_method=True)
        self.StreamBingoNumbers = channel.unary_stream(
                '/TestService/StreamBingoNumbers',
                request_serializer=test__pb2.BingoNumbersRequest.SerializeToString,
                response_deserializer=test__pb2.BingoNumbersResponse.FromString,
                _registered_method=True)
        self.ReceiveBingoNumbers = channel.unary_unary(
                '/TestService/ReceiveBingoNumbers',
                request_serializer=test__pb2.BingoNumbersRequest.SerializeToString,
                response_deserializer=test__pb2.BingoNumbersResponse.FromString,
                _registered_method=True)
        self.ConfirmReceipt = channel.unary_unary(
                '/TestService/ConfirmReceipt',
                request_serializer=test__pb2.ConfirmationRequest.SerializeToString,
                response_deserializer=test__pb2.ConfirmationResponse.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/TestService/SendMessage',
                request_serializer=test__pb2.MessageRequest.SerializeToString,
                response_deserializer=test__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.GetKeys = channel.unary_unary(
                '/TestService/GetKeys',
                request_serializer=test__pb2.KeyFilesRequest.SerializeToString,
                response_deserializer=test__pb2.KeyFilesResponse.FromString,
                _registered_method=True)
        self.GetBingoImages = channel.unary_stream(
                '/TestService/GetBingoImages',
                request_serializer=test__pb2.ImageRequest.SerializeToString,
                response_deserializer=test__pb2.ImageResponse.FromString,
                _registered_method=True)
        self.StreamCommandCodes = channel.unary_stream(
                '/TestService/StreamCommandCodes',
                request_serializer=test__pb2.CommandRequest.SerializeToString,
                response_deserializer=test__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.SendBalanceAdjustmentRequest = channel.unary_unary(
                '/TestService/SendBalanceAdjustmentRequest',
                request_serializer=test__pb2.BalanceAdjustmentRequest.SerializeToString,
                response_deserializer=test__pb2.BalanceAdjustmentResponse.FromString,
                _registered_method=True)
        self.StreamBalanceAdjustment = channel.unary_stream(
                '/TestService/StreamBalanceAdjustment',
                request_serializer=test__pb2.BalanceAdjustmentQuery.SerializeToString,
                response_deserializer=test__pb2.BalanceAdjustmentRequest.FromString,
                _registered_method=True)
        self.ConfirmBalanceAdjustment = channel.unary_unary(
                '/TestService/ConfirmBalanceAdjustment',
                request_serializer=test__pb2.BalanceAdjustmentConfirmation.SerializeToString,
                response_deserializer=test__pb2.BalanceAdjustmentResponse.FromString,
                _registered_method=True)


class TestServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request_iterator, context):
        """El servidor cloud espera que el cliente se conecte mediante streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamBingoNumbers(self, request, context):
        """Streaming desde el servidor para enviar números de bingo de manera proactiva
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveBingoNumbers(self, request, context):
        """Recibe números de bingo desde draw_processor.py
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmReceipt(self, request, context):
        """Confirmación de recepción de números de bingo (método unary)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Envío de mensajes genéricos como "heartbeat" o "ping"
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKeys(self, request, context):
        """Método para que el cliente solicite las llaves
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBingoImages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCommandCodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendBalanceAdjustmentRequest(self, request, context):
        """Nuevos métodos para ajuste de balances:
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamBalanceAdjustment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmBalanceAdjustment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=test__pb2.ConnectionRequest.FromString,
                    response_serializer=test__pb2.ConnectionResponse.SerializeToString,
            ),
            'StreamBingoNumbers': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamBingoNumbers,
                    request_deserializer=test__pb2.BingoNumbersRequest.FromString,
                    response_serializer=test__pb2.BingoNumbersResponse.SerializeToString,
            ),
            'ReceiveBingoNumbers': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveBingoNumbers,
                    request_deserializer=test__pb2.BingoNumbersRequest.FromString,
                    response_serializer=test__pb2.BingoNumbersResponse.SerializeToString,
            ),
            'ConfirmReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmReceipt,
                    request_deserializer=test__pb2.ConfirmationRequest.FromString,
                    response_serializer=test__pb2.ConfirmationResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=test__pb2.MessageRequest.FromString,
                    response_serializer=test__pb2.MessageResponse.SerializeToString,
            ),
            'GetKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKeys,
                    request_deserializer=test__pb2.KeyFilesRequest.FromString,
                    response_serializer=test__pb2.KeyFilesResponse.SerializeToString,
            ),
            'GetBingoImages': grpc.unary_stream_rpc_method_handler(
                    servicer.GetBingoImages,
                    request_deserializer=test__pb2.ImageRequest.FromString,
                    response_serializer=test__pb2.ImageResponse.SerializeToString,
            ),
            'StreamCommandCodes': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCommandCodes,
                    request_deserializer=test__pb2.CommandRequest.FromString,
                    response_serializer=test__pb2.CommandResponse.SerializeToString,
            ),
            'SendBalanceAdjustmentRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.SendBalanceAdjustmentRequest,
                    request_deserializer=test__pb2.BalanceAdjustmentRequest.FromString,
                    response_serializer=test__pb2.BalanceAdjustmentResponse.SerializeToString,
            ),
            'StreamBalanceAdjustment': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamBalanceAdjustment,
                    request_deserializer=test__pb2.BalanceAdjustmentQuery.FromString,
                    response_serializer=test__pb2.BalanceAdjustmentRequest.SerializeToString,
            ),
            'ConfirmBalanceAdjustment': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmBalanceAdjustment,
                    request_deserializer=test__pb2.BalanceAdjustmentConfirmation.FromString,
                    response_serializer=test__pb2.BalanceAdjustmentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('TestService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TestService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/TestService/Connect',
            test__pb2.ConnectionRequest.SerializeToString,
            test__pb2.ConnectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamBingoNumbers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/TestService/StreamBingoNumbers',
            test__pb2.BingoNumbersRequest.SerializeToString,
            test__pb2.BingoNumbersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveBingoNumbers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TestService/ReceiveBingoNumbers',
            test__pb2.BingoNumbersRequest.SerializeToString,
            test__pb2.BingoNumbersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TestService/ConfirmReceipt',
            test__pb2.ConfirmationRequest.SerializeToString,
            test__pb2.ConfirmationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TestService/SendMessage',
            test__pb2.MessageRequest.SerializeToString,
            test__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TestService/GetKeys',
            test__pb2.KeyFilesRequest.SerializeToString,
            test__pb2.KeyFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBingoImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/TestService/GetBingoImages',
            test__pb2.ImageRequest.SerializeToString,
            test__pb2.ImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCommandCodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/TestService/StreamCommandCodes',
            test__pb2.CommandRequest.SerializeToString,
            test__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendBalanceAdjustmentRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TestService/SendBalanceAdjustmentRequest',
            test__pb2.BalanceAdjustmentRequest.SerializeToString,
            test__pb2.BalanceAdjustmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamBalanceAdjustment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/TestService/StreamBalanceAdjustment',
            test__pb2.BalanceAdjustmentQuery.SerializeToString,
            test__pb2.BalanceAdjustmentRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmBalanceAdjustment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TestService/ConfirmBalanceAdjustment',
            test__pb2.BalanceAdjustmentConfirmation.SerializeToString,
            test__pb2.BalanceAdjustmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
